# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghomfc < Formula
  desc "Add GitHub Issues and Pull Requests to GitHub Projects
"
  homepage "https://github.com/suzuki-shunsuke/ghomfc"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghomfc/releases/download/v0.1.1/ghomfc_darwin_amd64.tar.gz"
      sha256 "66f1d5fe0b05008034f3207a866f6e62bd0572201c1a4a4498b729474e3c5179"

      def install
        bin.install "ghomfc"
        generate_completions_from_executable(bin/"ghomfc", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghomfc/releases/download/v0.1.1/ghomfc_darwin_arm64.tar.gz"
      sha256 "fb0260981f1e8827f3d4cbe1c1609e913388ceea55c2fecd38d72b352b451b49"

      def install
        bin.install "ghomfc"
        generate_completions_from_executable(bin/"ghomfc", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghomfc/releases/download/v0.1.1/ghomfc_linux_amd64.tar.gz"
        sha256 "dd2d1fb0d781a0fb4067bafdfe8063b586e618c82a4ff49e60388234d71352df"

        def install
          bin.install "ghomfc"
          generate_completions_from_executable(bin/"ghomfc", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghomfc/releases/download/v0.1.1/ghomfc_linux_arm64.tar.gz"
        sha256 "35ca5318f75ac1fd3045581258f1c411991ce1ac6aadbcc98dc81a993beb9846"

        def install
          bin.install "ghomfc"
          generate_completions_from_executable(bin/"ghomfc", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
  end

  test do
    system "#{bin}/ghomfc --version"
  end
end
