# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghomfc < Formula
  desc "Add GitHub Issues and Pull Requests to GitHub Projects
"
  homepage "https://github.com/suzuki-shunsuke/ghomfc"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghomfc/releases/download/v0.1.0/ghomfc_darwin_amd64.tar.gz"
      sha256 "8185bcc6a415ea4054cf8b380c74c72dd9fa52cfed29aa8e76d77af662985547"

      def install
        bin.install "ghomfc"
        generate_completions_from_executable(bin/"ghomfc", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghomfc/releases/download/v0.1.0/ghomfc_darwin_arm64.tar.gz"
      sha256 "2e784243d657305da39a5240594dd43d432bc258e5fd78c34388e74d52a94f01"

      def install
        bin.install "ghomfc"
        generate_completions_from_executable(bin/"ghomfc", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghomfc/releases/download/v0.1.0/ghomfc_linux_amd64.tar.gz"
        sha256 "0afa7316ef41c4450b65773ca6be07c7dc6c1e3afe746a4a6a3cb3f48286faaf"

        def install
          bin.install "ghomfc"
          generate_completions_from_executable(bin/"ghomfc", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghomfc/releases/download/v0.1.0/ghomfc_linux_arm64.tar.gz"
        sha256 "469d390061547c162499859d029340b92707da8e8aecfe30c22ba982fb1bbf5f"

        def install
          bin.install "ghomfc"
          generate_completions_from_executable(bin/"ghomfc", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
  end

  test do
    system "#{bin}/ghomfc --version"
  end
end
