# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghomfc" do
  name "ghomfc"
  desc "Add GitHub Issues and Pull Requests to GitHub Projects
"
  homepage "https://github.com/suzuki-shunsuke/ghomfc"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghomfc"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghomfc/releases/download/v#{version}/ghomfc_darwin_amd64.tar.gz"
      sha256 "04e5ebca5461100a0486409f96411d6c15901e210880ac91689cf3602516a5fa"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghomfc/releases/download/v#{version}/ghomfc_darwin_arm64.tar.gz"
      sha256 "a996268bbda2bc898567a852271e8246d8908a36b03b55c297bd61693d8f6b67"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghomfc/releases/download/v#{version}/ghomfc_linux_amd64.tar.gz"
      sha256 "1deee2589107dc088471040ebf7577ba9fcc3e8408582dd62358116db13cf89a"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghomfc/releases/download/v#{version}/ghomfc_linux_arm64.tar.gz"
      sha256 "9b0c7468684684d4b8cef7bef929ec5c69940c462c714ab699f1e191757a714b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghomfc"]
    end
  end

  # No zap stanza required
end
