# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghomfc" do
  desc "Add GitHub Issues and Pull Requests to GitHub Projects
"
  homepage "https://github.com/suzuki-shunsuke/ghomfc"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghomfc"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghomfc/releases/download/v0.1.2/ghomfc_darwin_amd64.tar.gz"
      sha256 "f0aea24e66a6c9b4bafbfdb525724db4950d78156ace85d76885a491d2fc02dc"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghomfc/releases/download/v0.1.2/ghomfc_darwin_arm64.tar.gz"
      sha256 "44855024ebab629fc4f575d8ebd96a25b3443225485a21e4cf327dfc28be815e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghomfc/releases/download/v0.1.2/ghomfc_linux_amd64.tar.gz"
      sha256 "23c5579671ca00b7c86e7bcc2f3dcc73e8821f1edaf54c236efbbdd7905a5502"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghomfc/releases/download/v0.1.2/ghomfc_linux_arm64.tar.gz"
      sha256 "1ecebc76ece7918a4c616e8b7c296376a7c215877ba1aa5bb2828c36831c8227"
    end
  end

  # No zap stanza required
end
